### ISSUE TITLE
Nautlius fails to start after install, assertion 'g_type_from_name (name) == 0' failed

### ISSUE THREAD

**Issue by neekfenwick** [Lich-Corals/linux-file-converter-addon#42] opened 2024-10-04 03:30 UTC
**Describe the bug**
After copying the `nautilus-fileconverter.py` file into `/usr/share/nautilus-python/extensions` on my Fedora 40 system, nautilus fails to start.  Moving the .py file back out of the extensions directory lets it start again.

There are no other files in `/usr/share/nautilus-python/extensions`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install all dependencies (pillow etc)
2. Copy `nautilus-fileconverter.py` to `/usr/share/nautilus-python/extensions`
3. Run `nautilus` from the command line
4. No window appears

**Expected behaviour**
Nautilus should at least open.

**Screenshots**
n/a

**System information**
Basic information about the used OS
 - OS Name: Fedora 40
 - Package manager: dnf
 - Gnome version (If you are using Gnome): GNOME 46
 - Nautilus version (If you are using Nautilus) (`nautilus --version`): GNOME nautilus 46.2
 - Python version (`python3 --version`): Python 3.12.6
 - pip version (`pip --version`): pip 23.3.2 from /usr/lib/python3.12/site-packages/pip (python 3.12)
 - File converter version (specified at the start of the script): 001002010

**Nautilus errors (If you are using Nautilus)**
With nautilus-fileconverter.py installed:
```
$ G_DEBUG="all" NAUTILUS_DEBUG="All" nautilus
** Message: 10:22:22.530: Connecting to org.freedesktop.Tracker3.Miner.Files
ModuleNotFoundError: No module named 'nautilus-gsconnect'

(org.gnome.Nautilus:468222): GLib-GObject-CRITICAL **: 10:22:22.693: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
Trace/breakpoint trap (core dumped)
```
Result - nautilus does not open.

Without nautilus-fileconverter.py installed:
```
$ G_DEBUG="all" NAUTILUS_DEBUG="All" nautilus
** Message: 10:22:49.514: Connecting to org.freedesktop.Tracker3.Miner.Files
ModuleNotFoundError: No module named 'nautilus-gsconnect'
```
Result - nautilus runs OK.

**Additional context**
I think the nautilus-gsconnect message can be ignored, it appears with or without this script installed and doesn't seem to be causing any harm.

**Comment by Lich-Corals** [comment] 2024-10-11 10:05
I could reproduce the issue and just published a fix.
Please update your nautilus-fileconverter.py file from the repository, then run `nautilus -q` and start nautilus again.
You can close the issue, if it is solved; if not, just continue the conversation.

**Comment by neekfenwick** [comment] 2024-10-15 07:41
Sorry @Lich-Corals I only just noticed this.  I am not very experienced with Python or Nautilus extensions.  I replaced the file in /usr/share/nautilus-python/extensions and, indeed, it doesn't crash immediately any more, so this is progress :)

On first run, I could not see any change to the context menu, so I checked `journalctl -xe`:

Oct 15 14:14:02 uberneek systemd[2967]: Started dbus-:1.2-org.gnome.Nautilus@3.service.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 1649.
Oct 15 14:14:02 uberneek nautilus[351180]: Connecting to org.freedesktop.Tracker3.Miner.Files
Oct 15 14:14:02 uberneek nautilus[351180]: detected unhandled Python exception in 'nautilus'
Oct 15 14:14:02 uberneek nautilus[351180]: ModuleNotFoundError: No module named 'nautilus-gsconnect'
Oct 15 14:14:02 uberneek nautilus[351180]: /usr/share/nautilus-python/extensions/nautilus-fileconverter.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to e>
Oct 15 14:14:02 uberneek nautilus[351180]:   from gi.repository import GObject, Gtk, Nautilus
Oct 15 14:14:02 uberneek nautilus[351180]: Traceback (most recent call last):
Oct 15 14:14:02 uberneek nautilus[351180]:   File "/usr/share/nautilus-python/extensions/nautilus-fileconverter.py", line 96, in <module>
Oct 15 14:14:02 uberneek nautilus[351180]:     if _config["automaticUpdates"]:
Oct 15 14:14:02 uberneek nautilus[351180]:        ^^^^^^^
Oct 15 14:14:02 uberneek nautilus[351180]: NameError: name '_config' is not defined
Oct 15 14:14:02 uberneek nautilus[351180]: WARNING(Nautilus-file-converter)(001): "jxlpy" not found. View https://github.com/Lich-Corals/linux-file-converter-addon/blob/main/markdown/errors-and-warnings.md for more information.
Oct 15 14:14:02 uberneek nautilus[351180]: WARNING(Nautilus-file-converter)(003): No permission to self-update; script at "/usr/share/nautilus-python/extensions/nautilus-fileconverter.py" is not writeable. View https://github.com/L>
Oct 15 14:14:02 uberneek nautilus[351180]: WARNING(Nautilus-file-converter)(004): No permission to write configuration file; "/usr/share/nautilus-python/extensions" is not writeable. View https://github.com/Lich-Corals/linux-file-c>
Oct 15 14:14:03 uberneek systemd[2967]: Started dbus-:1.2-org.gnome.NautilusPreviewer@3.service.

As before I think we can ignore the `gsconnect` message, and the `jxlpy` warning seems non fatal, and of the other two warnings:

"No permission to write configuration file; "/usr/share/nautilus-python/extensions" is not writeable" -  this directory had permissions "rwxr-xr-x root root" so I guess when I run nautilus as my unprivileged user it cannot write to that folder.  If I `chmod` the folder `a+w` and restart nautilus then a `__pycache__` folder appears containing a single .pyc file.  I still get no new context menus in Nautilus.  I had followed the basic instructions to 'install globally', but maybe these need to be amended if an unprivileged user cannot actually run it when the folder the script is in is owned by root and is not writable?

The "NameError: name '_config' is not defined" error in the journal still seems to be serious. From a quick look at the code, it looks like it's trying to load a JSON file `{currentPath}/NFC43-Config.json` and assign it to `_config`, so I can only assume that's failing somehow, leaving `_config` undefined and producing the `NameError` when dereferenced for `_config["automaticUpdates"]`.  I don't see a `NFC43-Config.json` anywhere on my file system.

**Comment by Lich-Corals** [comment] 2024-10-15 08:02
Alright, I think I see what the problem is. It is, as you already saw, the JSON file, which cannot be loaded.
As far as I see, the program doesn't create a config file if it doesn't exist already. I will push another quick fix for this, probably today.
For a quick solution, you could just create a config file in the `extensions` folder `NFC43-Config.json` and with just `[]` inside of it. With the next launch, the program should write the default configuration into the file.

**Comment by Lich-Corals** [comment] 2024-10-15 09:15
The update is published and I tested it in as many situations as I could.
Please update your .py file again and run `nautilus -q` / `nautilus` to check if it works.

**Comment by neekfenwick** [comment] 2024-10-16 05:06
Thank you for your attention to this :) I think you've fixed it, I do now see the context menu in nautilus.  I've set permissions for my /usr/share/nautilus-python/extensions folder back to only writable by root, and it still works.

On a side note, it still looks like it can't write its config file, and I may be being rather stupid here but the 'For a system-wide installation' option given in https://github.com/Lich-Corals/linux-file-converter-addon/blob/main/markdown/install-nautilus.md says to copy the file into a folder that's usually only writable by root, so would the config file always fail to write in this situation? (unless you run nautilus as root so the process has write permission to that folder, which is unusual)  If I copy the .py script into ~/.local/share/nautilus-python/extensions instead and restart nautilus, then the NFC43-Config.json file is written and is useful.

I'll go ahead with the ~/.local/share installation location instead of /usr/share for me, as it's a single user workstation.

**Comment by Lich-Corals** [comment] 2024-10-16 06:29
I'm glad your issue is fixed.

Yes, the config file is almost useless without permission to write it. If it is correctly generated, the program will still read it but if new options are added with an update, the file won't be updated too, unless the write permissions are granted again.
I thought I had warned about the permission problems in install.md; I will add another note in the instructions about this.

**Closed** 2024-10-16 06:29 UTC
